services:
  mysql:
    image: mysql:8.0
    container_name: appointment-mysql
    environment:
      MYSQL_DATABASE: appointment_app
      MYSQL_USER: appointment_user
      MYSQL_PASSWORD: appointment_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: appointment-redis
    ports:
      - "6379:6379"

  adminer:
    image: adminer:latest
    container_name: appointment-adminer
    depends_on:
      - mysql
    ports:
      - "8082:8080"

volumes:
  mysql_data:
