spring:
  application:
    name: appointment-app
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/appointment_app}
    username: ${SPRING_DATASOURCE_USERNAME:appointment_user}
    password: ${SPRING_DATASOURCE_PASSWORD:appointment_password}
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: info
